### ISSUE TITLE
Erro banco de dados

### ISSUE THREAD

**Issue by guilherme-proconsult** [SidSan97/proconsult#1]
Bom dia Signei, tudo bem?
Estou fazendo a avaliação do seu projeto, porém estou tendo problemas para executar.
Segui as instruções do seu README e mesmo assim estou recebendo erro sobre o banco de dados.
No README você diz para alterar as configurações no caminho api/application/config/database.php, porém ao iniciar o projeto recebo o seguinte erro:
![image](https://github.com/SidSan97/proconsult/assets/61846542/c28d70c8-a9ea-4371-a27c-c4fa03d4861d)

Meu arquivo:
![image](https://github.com/SidSan97/proconsult/assets/61846542/d2c4d7c2-2c01-4e47-ab28-453b80a0cee0)

Mesmo tentando ignorar essa mensagem, é claro que o projeto continua com erros:
![image](https://github.com/SidSan97/proconsult/assets/61846542/cfdf1591-5e45-452b-903f-b3c466566327)

Caso não consiga arrumar até o final de dia, infelizmente, seu projeto não será avaliado.

**Comment by SidSan97** [comment]
Entrei no projeto e coloquei o mesmo nome e peguei o mesmo erro que você teve

![image](https://github.com/SidSan97/proconsult/assets/44247661/0e53dfd6-5376-46f4-9219-e75bbc484233)
![image](https://github.com/SidSan97/proconsult/assets/44247661/68a1934a-6384-4bb0-9e93-fd071ebcef58)

Então fui no PHPMyAdmin e criei uma nova base de dados com o nome _teste_candidatos_ 

![image](https://github.com/SidSan97/proconsult/assets/44247661/dfe7cf04-1a0f-46a4-b469-65578152607f)

E copiei a estrutura do arquivo que se encontra na pasta **_database_** nesta nova base de dados

![image](https://github.com/SidSan97/proconsult/assets/44247661/ea7e7511-ed12-41ab-ab2f-6851952d61ba)

E o erro foi resolvido

![image](https://github.com/SidSan97/proconsult/assets/44247661/38208fee-bac0-4c08-a452-b8d5105e27cd)
